# Site settings
title: MovingData
header-img: img/home-bg.jpg
email: tylermalin@gmail.com
description: "Exploring The Relationship Between Complex Data and Visual Communication"
baseurl: "/tylermalin.github.io"
url: "http://tylermalin.github.io"
twitter_username: @tylermalin
github_username:  tylermalin
facebook_username:  tylermalin

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
